# Generated by Django 6.0.1 on 2026-01-26 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("plate_number", models.CharField(max_length=20, unique=True)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("compactor", "Compactor Truck"),
                            ("rear_loader", "Rear Loader"),
                            ("side_loader", "Side Loader"),
                            ("roll_off", "Roll-Off Truck"),
                        ],
                        max_length=20,
                    ),
                ),
                ("capacity_kg", models.FloatField()),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("maintenance", "Under Maintenance"),
                        ],
                        default="inactive",
                        max_length=20,
                    ),
                ),
                ("last_location_lat", models.FloatField(blank=True, null=True)),
                ("last_location_lng", models.FloatField(blank=True, null=True)),
                ("last_location_update", models.DateTimeField(blank=True, null=True)),
                ("fuel_level", models.IntegerField(default=100)),
                ("mileage", models.IntegerField(default=0)),
                ("last_maintenance_date", models.DateField(blank=True, null=True)),
                ("next_maintenance_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="companies.wastecompany",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Driver",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("license_number", models.CharField(max_length=50, unique=True)),
                ("license_expiry", models.DateField()),
                (
                    "current_status",
                    models.CharField(
                        choices=[
                            ("on_duty", "On Duty"),
                            ("off_duty", "Off Duty"),
                            ("on_leave", "On Leave"),
                        ],
                        default="off_duty",
                        max_length=20,
                    ),
                ),
                ("total_collections", models.IntegerField(default=0)),
                ("rating", models.FloatField(default=5.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="drivers",
                        to="companies.wastecompany",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assigned_vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_driver",
                        to="fleet.vehicle",
                    ),
                ),
            ],
        ),
    ]
