# Generated by Django 6.0.1 on 2026-01-26 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CityWideReport",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=200)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("total_waste_generated_tons", models.FloatField(default=0)),
                ("total_waste_collected_tons", models.FloatField(default=0)),
                ("recycling_rate_percentage", models.FloatField(default=0)),
                ("active_companies", models.IntegerField(default=0)),
                ("active_vehicles", models.IntegerField(default=0)),
                ("active_zones", models.IntegerField(default=0)),
                ("total_requests", models.IntegerField(default=0)),
                ("completion_rate", models.FloatField(default=0)),
                ("average_response_time", models.FloatField(default=0)),
                ("zone_breakdown", models.JSONField(blank=True, default=dict)),
                ("company_breakdown", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PerformanceReport",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("monthly", "Monthly"),
                            ("quarterly", "Quarterly"),
                            ("yearly", "Yearly"),
                        ],
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("total_collections", models.IntegerField(default=0)),
                ("completed_collections", models.IntegerField(default=0)),
                ("missed_collections", models.IntegerField(default=0)),
                ("average_response_time_hours", models.FloatField(default=0)),
                ("total_waste_collected_kg", models.FloatField(default=0)),
                ("recycled_waste_kg", models.FloatField(default=0)),
                ("customer_satisfaction_rating", models.FloatField(default=0)),
                ("complaints_received", models.IntegerField(default=0)),
                ("complaints_resolved", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="performance_reports",
                        to="companies.wastecompany",
                    ),
                ),
                (
                    "generated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
