# Generated by Django 6.0.1 on 2026-01-26 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("companies", "0001_initial"),
        ("fleet", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionRequest",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "waste_type",
                    models.CharField(
                        choices=[
                            ("general", "General Waste"),
                            ("recyclable", "Recyclable"),
                            ("hazardous", "Hazardous"),
                            ("organic", "Organic/Compostable"),
                            ("bulky", "Bulky Items"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity_bags", models.IntegerField(default=1)),
                ("estimated_weight_kg", models.FloatField(blank=True, null=True)),
                ("preferred_date", models.DateField()),
                (
                    "preferred_time",
                    models.CharField(
                        choices=[
                            ("morning", "Morning (6AM-12PM)"),
                            ("afternoon", "Afternoon (12PM-6PM)"),
                            ("evening", "Evening (6PM-9PM)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("address", models.TextField()),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("special_instructions", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("estimated_arrival", models.DateTimeField(blank=True, null=True)),
                ("collected_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="companies.wastecompany",
                    ),
                ),
                (
                    "assigned_driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fleet.driver",
                    ),
                ),
                (
                    "assigned_vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fleet.vehicle",
                    ),
                ),
                (
                    "resident",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CollectionRecord",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("collected_at", models.DateTimeField()),
                ("actual_weight_kg", models.FloatField(blank=True, null=True)),
                (
                    "photo_proof",
                    models.ImageField(
                        blank=True, null=True, upload_to="collection_proofs/"
                    ),
                ),
                ("resident_signature", models.TextField(blank=True)),
                ("driver_notes", models.TextField(blank=True)),
                ("rating", models.IntegerField(blank=True, null=True)),
                ("feedback", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "driver",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fleet.driver",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="fleet.vehicle",
                    ),
                ),
                (
                    "collection_request",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="record",
                        to="collections.collectionrequest",
                    ),
                ),
            ],
        ),
    ]
